import time

import pygame
pygame.init()

from pygame import mixer

music = pygame.mixer.music.load('Windows XP Startup.wav')
pygame.mixer.music.play(1)
time.sleep(3)
print()
print("Hi, what\'s your name?")
time.sleep(1)
name = input()
time.sleep(1)

print(name + ", Would you like to hear a few jokes?")

answer =str(input("y for YES and n for NO: "))
if answer == 'y':
  print("Great, " + name + " Please wait a moment...")
elif answer == 'Y':
  print("Great, " + name + " Please wait a moment...")
if answer == 'n':
  print ("OK.")
  music = pygame.mixer.music.load('Windows XP Shutdown.wav')
  pygame.mixer.music.play(1)
  exit()
elif answer == "N":
  print ("OK.")
  music = pygame.mixer.music.load('Windows XP Shutdown.wav')
  pygame.mixer.music.play(1)
  exit()

print("Loading...")
time.sleep(1)
print("Loading...")
time.sleep(1)
print("Loading...")
time.sleep(1)
input("Press enter to continue: ")
time.sleep(1)
print("Ok. YOUR JOKES ARE COMING RIGHT UP!")
time.sleep(1)

print("Why did the spider go to the computer?")
time.sleep(2.5)
print("To go the the World Wide Web!")
time.sleep(2.25)
print("Press enter to hear the next one")
input()
time.sleep(.25)
print("Here, " + name + ", This ones for you!")
time.sleep(1.25)
print("What do you call a Cavemans fart?")

input()
 
print("A blast from the past!")
time.sleep(1.75)
print("Press enter to hear the next one")
input()
answer =str(input("Would you like to listen to music?: y for YES and n for NO: "))
if answer == 'y':
    music = pygame.mixer.music.load('Razihel - A Song About You [NCS Release].mp3')
    pygame.mixer.music.play(-1)
    time.sleep(.5)
    print("Playing some music!")
elif answer == 'Y':
  music = pygame.mixer.music.load('Razihel - A Song About You [NCS Release].mp3')
  pygame.mixer.music.play(-1)
  time.sleep(.5)
  print("Playing some music!")
elif answer == "N":
    print("OK!")
elif answer == "n":
  time.sleep(.25)
time.sleep(1)
print("Why did the dad tell the child to stop coding?")
time.sleep(2.5)
print("Because it was to confusing!")
time.sleep(2)
print("Press enter to hear the next one")
input()
time.sleep(.25)
print("What do you call a fish wearing a bowtie?")
time.sleep(2.25)
print("Sofishticated.")
time.sleep(2)
print("Press enter to hear the next one")
input()
time.sleep(.25)
print("Want anymore JOKES?")
answer =str(input("y for YES and n for NO: "))
if answer == 'y':
  print("Great, " + name + " Please wait a moment...")
elif answer == 'Y':
  print("Great, " + name + " Please wait a moment...")
if answer == 'n':
  print ("OK.")
  music = pygame.mixer.music.load('Windows XP Shutdown.wav')
  pygame.mixer.music.play(1)
  exit()
elif answer == "N":
  print ("OK.")
  music = pygame.mixer.music.load('Windows XP Shutdown.wav')
  pygame.mixer.music.play(1)
  exit()

time.sleep(.5)
print("What’s the best thing about Switzerland?")
time.sleep(2)
print("I don’t know, but the flag is a big plus.")
time.sleep(2.5)
print("Press enter to hear the next one")
input()
print("Did you hear about the mathematician who’s afraid of negative numbers?")
time.sleep(2)
print("He’ll stop at nothing to avoid them.")
time.sleep(2.5)
print("Press enter to  here the next one")
input()
print("What did the Shark say when he ate the ClownFish??")
time.sleep(2)
print("This tastes a little funny.")
time.sleep(2.5)
print("Press enter to hear the next one")
input()
print("Two artists had an art contest...")
time.sleep(2)
print("They had a draw!")
time.sleep(2.5)
print("Press enter to hear the next one")
input()
print("Please rate us...")
print("If you rate 5 stars, go to https://creeper39x.webflow.io/")
time.sleep(10)
print("What does a zombie vegetarian eat?")
time.sleep(2)
print("Grraaaaiiiiiinnnnssss")
time.sleep(2.5)
print("Error 404, a zombie has eaten you!")
time.sleep(1.5)
music = pygame.mixer.music.load('Windows XP Startup.wav')
pygame.mixer.music.play(1)
time.sleep(3)
exit()


